login: &login
  adapter: mysql
  username: root
  password: 
  socket: /tmp/mysql.sock
  
development:
  <<: *login
  database: albumdy_development

test:
  <<: *login
  database: albumdy_test

production:
  adapter: mysql
  username: root
  password: 210474dr44
  socket: /var/run/mysqld/mysqld.sock
  database: albumdy